jobs:
  build:
    runs-on: ubuntu-20.04 
    steps: 
      - uses: actions/checkout@v2.3.1
      - run: dotnet build

  #test:
  #analyze:
  #package:
  #deploy:

name: build

on:
  push:
    branches:
      - master