
jobs: 
  build: 
    runs-on: ubuntu-20.04
    steps: 
      - 
        uses: actions/checkout@v2.3.1
      - 
        run: "dotnet build"
  test: 
    runs-on: "ubuntu-20.04 - uses:actions/checkout@v2.3.1 - run:dotnet test"
name: build
true: 
  push: 
    branches: 
      - master