
jobs: 
  build: 
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2.3.1
      - run: dotnet build
  test: 
    runs-on: ubuntu-20.04 
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet test -p:CollectCoverage=true
  analyze:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet tool install --global dotnet-sonarscanner
      - run: |
        dotnet sonarscanner begin -o 'kyeel1' -k 'kyeel1_Week_4' -d:sonnar.login='1b54d9ebb67465d4489d7d7a2fdf4a9c6785ae77'
        dotnet build
        dotnet test -p:CollectCoverage=true
        dotnet sonarscanner end -d:sonnar.login='1b54d9ebb67465d4489d7d7a2fdf4a9c6785ae77'
name: build
on: 
  push: 
    branches: 
      - master